#!/usr/bin/env zsh
# NOTE: Uncomment when you want to take a profile
# zmodload zsh/zprof

typeset -U path manpath infopath fpath

export \
  XDG_CONFIG_HOME="${HOME}/.config" \
  XDG_CACHE_HOME="${HOME}/.cache" \
  XDG_DATA_HOME="${HOME}/.local/share" \
  XDG_STATE_HOME="${HOME}/.local/state"

export LANG='en_US.UTF-8'
