# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: 'CI'

on:
  - 'pull_request'

permissions: {}

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  ci:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
    timeout-minutes: 10
    steps:
      - uses: 'actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1' # v7
        with:
          persist-credentials: false
      - uses: 'cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342' # v31
      - uses: 'DeterminateSystems/flake-checker-action@de924abd783455e8429c858962b9e43062d19da1' # v13
      - run: |
          make check
